// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/interfaces.go -destination=./internal/mocks/repository_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	entity "github.com/limbo/discipline/pkg/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersRepository is a mock of UsersRepository interface.
type MockUsersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepositoryMockRecorder
	isgomock struct{}
}

// MockUsersRepositoryMockRecorder is the mock recorder for MockUsersRepository.
type MockUsersRepositoryMockRecorder struct {
	mock *MockUsersRepository
}

// NewMockUsersRepository creates a new mock instance.
func NewMockUsersRepository(ctrl *gomock.Controller) *MockUsersRepository {
	mock := &MockUsersRepository{ctrl: ctrl}
	mock.recorder = &MockUsersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepository) EXPECT() *MockUsersRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUsersRepository) Create(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUsersRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsersRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUsersRepository) Delete(ctx context.Context, uid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsersRepositoryMockRecorder) Delete(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsersRepository)(nil).Delete), ctx, uid)
}

// FindByID mocks base method.
func (m *MockUsersRepository) FindByID(ctx context.Context, uid uuid.UUID) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, uid)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUsersRepositoryMockRecorder) FindByID(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUsersRepository)(nil).FindByID), ctx, uid)
}

// FindByName mocks base method.
func (m *MockUsersRepository) FindByName(ctx context.Context, name string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockUsersRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockUsersRepository)(nil).FindByName), ctx, name)
}

// Update mocks base method.
func (m *MockUsersRepository) Update(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUsersRepositoryMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsersRepository)(nil).Update), ctx, user)
}

// MockHabitsRepository is a mock of HabitsRepository interface.
type MockHabitsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHabitsRepositoryMockRecorder
	isgomock struct{}
}

// MockHabitsRepositoryMockRecorder is the mock recorder for MockHabitsRepository.
type MockHabitsRepositoryMockRecorder struct {
	mock *MockHabitsRepository
}

// NewMockHabitsRepository creates a new mock instance.
func NewMockHabitsRepository(ctrl *gomock.Controller) *MockHabitsRepository {
	mock := &MockHabitsRepository{ctrl: ctrl}
	mock.recorder = &MockHabitsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHabitsRepository) EXPECT() *MockHabitsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHabitsRepository) Create(ctx context.Context, habit *entity.Habit) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, habit)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHabitsRepositoryMockRecorder) Create(ctx, habit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHabitsRepository)(nil).Create), ctx, habit)
}

// Delete mocks base method.
func (m *MockHabitsRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHabitsRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHabitsRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockHabitsRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Habit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Habit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockHabitsRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockHabitsRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockHabitsRepository) GetByUserID(ctx context.Context, uid uuid.UUID, limit, offset int) ([]*entity.Habit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, uid, limit, offset)
	ret0, _ := ret[0].([]*entity.Habit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockHabitsRepositoryMockRecorder) GetByUserID(ctx, uid, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockHabitsRepository)(nil).GetByUserID), ctx, uid, limit, offset)
}

// Update mocks base method.
func (m *MockHabitsRepository) Update(ctx context.Context, habit *entity.Habit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, habit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHabitsRepositoryMockRecorder) Update(ctx, habit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHabitsRepository)(nil).Update), ctx, habit)
}

// MockHabitChecksRepository is a mock of HabitChecksRepository interface.
type MockHabitChecksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHabitChecksRepositoryMockRecorder
	isgomock struct{}
}

// MockHabitChecksRepositoryMockRecorder is the mock recorder for MockHabitChecksRepository.
type MockHabitChecksRepositoryMockRecorder struct {
	mock *MockHabitChecksRepository
}

// NewMockHabitChecksRepository creates a new mock instance.
func NewMockHabitChecksRepository(ctrl *gomock.Controller) *MockHabitChecksRepository {
	mock := &MockHabitChecksRepository{ctrl: ctrl}
	mock.recorder = &MockHabitChecksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHabitChecksRepository) EXPECT() *MockHabitChecksRepositoryMockRecorder {
	return m.recorder
}

// CountByHabitID mocks base method.
func (m *MockHabitChecksRepository) CountByHabitID(ctx context.Context, habitID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByHabitID", ctx, habitID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByHabitID indicates an expected call of CountByHabitID.
func (mr *MockHabitChecksRepositoryMockRecorder) CountByHabitID(ctx, habitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByHabitID", reflect.TypeOf((*MockHabitChecksRepository)(nil).CountByHabitID), ctx, habitID)
}

// Create mocks base method.
func (m *MockHabitChecksRepository) Create(ctx context.Context, habitID uuid.UUID, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, habitID, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHabitChecksRepositoryMockRecorder) Create(ctx, habitID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHabitChecksRepository)(nil).Create), ctx, habitID, date)
}

// Delete mocks base method.
func (m *MockHabitChecksRepository) Delete(ctx context.Context, habitID uuid.UUID, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, habitID, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHabitChecksRepositoryMockRecorder) Delete(ctx, habitID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHabitChecksRepository)(nil).Delete), ctx, habitID, date)
}

// Exists mocks base method.
func (m *MockHabitChecksRepository) Exists(ctx context.Context, habitID uuid.UUID, date time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, habitID, date)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockHabitChecksRepositoryMockRecorder) Exists(ctx, habitID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockHabitChecksRepository)(nil).Exists), ctx, habitID, date)
}

// GetByHabitAndDateRange mocks base method.
func (m *MockHabitChecksRepository) GetByHabitAndDateRange(ctx context.Context, habitID uuid.UUID, from, to time.Time) ([]entity.HabitCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHabitAndDateRange", ctx, habitID, from, to)
	ret0, _ := ret[0].([]entity.HabitCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHabitAndDateRange indicates an expected call of GetByHabitAndDateRange.
func (mr *MockHabitChecksRepositoryMockRecorder) GetByHabitAndDateRange(ctx, habitID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHabitAndDateRange", reflect.TypeOf((*MockHabitChecksRepository)(nil).GetByHabitAndDateRange), ctx, habitID, from, to)
}

// GetCurrentStreak mocks base method.
func (m *MockHabitChecksRepository) GetCurrentStreak(ctx context.Context, habitID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentStreak", ctx, habitID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentStreak indicates an expected call of GetCurrentStreak.
func (mr *MockHabitChecksRepositoryMockRecorder) GetCurrentStreak(ctx, habitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentStreak", reflect.TypeOf((*MockHabitChecksRepository)(nil).GetCurrentStreak), ctx, habitID)
}

// GetLastCheckDate mocks base method.
func (m *MockHabitChecksRepository) GetLastCheckDate(ctx context.Context, habitID uuid.UUID) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCheckDate", ctx, habitID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCheckDate indicates an expected call of GetLastCheckDate.
func (mr *MockHabitChecksRepositoryMockRecorder) GetLastCheckDate(ctx, habitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCheckDate", reflect.TypeOf((*MockHabitChecksRepository)(nil).GetLastCheckDate), ctx, habitID)
}

// GetMaxStreak mocks base method.
func (m *MockHabitChecksRepository) GetMaxStreak(ctx context.Context, habitID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxStreak", ctx, habitID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxStreak indicates an expected call of GetMaxStreak.
func (mr *MockHabitChecksRepositoryMockRecorder) GetMaxStreak(ctx, habitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxStreak", reflect.TypeOf((*MockHabitChecksRepository)(nil).GetMaxStreak), ctx, habitID)
}

// MockDBConfig is a mock of DBConfig interface.
type MockDBConfig struct {
	ctrl     *gomock.Controller
	recorder *MockDBConfigMockRecorder
	isgomock struct{}
}

// MockDBConfigMockRecorder is the mock recorder for MockDBConfig.
type MockDBConfigMockRecorder struct {
	mock *MockDBConfig
}

// NewMockDBConfig creates a new mock instance.
func NewMockDBConfig(ctrl *gomock.Controller) *MockDBConfig {
	mock := &MockDBConfig{ctrl: ctrl}
	mock.recorder = &MockDBConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBConfig) EXPECT() *MockDBConfigMockRecorder {
	return m.recorder
}

// ConnString mocks base method.
func (m *MockDBConfig) ConnString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnString")
	ret0, _ := ret[0].(string)
	return ret0
}

// ConnString indicates an expected call of ConnString.
func (mr *MockDBConfigMockRecorder) ConnString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnString", reflect.TypeOf((*MockDBConfig)(nil).ConnString))
}

// MockPgConnection is a mock of PgConnection interface.
type MockPgConnection struct {
	ctrl     *gomock.Controller
	recorder *MockPgConnectionMockRecorder
	isgomock struct{}
}

// MockPgConnectionMockRecorder is the mock recorder for MockPgConnection.
type MockPgConnectionMockRecorder struct {
	mock *MockPgConnection
}

// NewMockPgConnection creates a new mock instance.
func NewMockPgConnection(ctrl *gomock.Controller) *MockPgConnection {
	mock := &MockPgConnection{ctrl: ctrl}
	mock.recorder = &MockPgConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgConnection) EXPECT() *MockPgConnectionMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockPgConnection) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockPgConnectionMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockPgConnection)(nil).Begin), ctx)
}

// Exec mocks base method.
func (m *MockPgConnection) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockPgConnectionMockRecorder) Exec(ctx, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockPgConnection)(nil).Exec), varargs...)
}

// Ping mocks base method.
func (m *MockPgConnection) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPgConnectionMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPgConnection)(nil).Ping), ctx)
}

// Query mocks base method.
func (m *MockPgConnection) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockPgConnectionMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPgConnection)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockPgConnection) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockPgConnectionMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockPgConnection)(nil).QueryRow), varargs...)
}
