// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/interfaces.go -destination=./internal/mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	service "github.com/limbo/discipline/internal/service"
	entity "github.com/limbo/discipline/pkg/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// DeleteAccount mocks base method.
func (m *MockUserService) DeleteAccount(ctx context.Context, id uuid.UUID, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, id, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockUserServiceMockRecorder) DeleteAccount(ctx, id, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockUserService)(nil).DeleteAccount), ctx, id, password)
}

// GetByID mocks base method.
func (m *MockUserService) GetByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserService)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockUserService) GetByName(ctx context.Context, name string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockUserServiceMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockUserService)(nil).GetByName), ctx, name)
}

// Login mocks base method.
func (m *MockUserService) Login(ctx context.Context, name, password string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, name, password)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceMockRecorder) Login(ctx, name, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserService)(nil).Login), ctx, name, password)
}

// Register mocks base method.
func (m *MockUserService) Register(ctx context.Context, req *service.RegisterRequest) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserService)(nil).Register), ctx, req)
}

// MockHabitsService is a mock of HabitsService interface.
type MockHabitsService struct {
	ctrl     *gomock.Controller
	recorder *MockHabitsServiceMockRecorder
	isgomock struct{}
}

// MockHabitsServiceMockRecorder is the mock recorder for MockHabitsService.
type MockHabitsServiceMockRecorder struct {
	mock *MockHabitsService
}

// NewMockHabitsService creates a new mock instance.
func NewMockHabitsService(ctrl *gomock.Controller) *MockHabitsService {
	mock := &MockHabitsService{ctrl: ctrl}
	mock.recorder = &MockHabitsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHabitsService) EXPECT() *MockHabitsServiceMockRecorder {
	return m.recorder
}

// CreateHabit mocks base method.
func (m *MockHabitsService) CreateHabit(ctx context.Context, uid uuid.UUID, req service.CreateHabitRequest) (*entity.Habit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHabit", ctx, uid, req)
	ret0, _ := ret[0].(*entity.Habit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHabit indicates an expected call of CreateHabit.
func (mr *MockHabitsServiceMockRecorder) CreateHabit(ctx, uid, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHabit", reflect.TypeOf((*MockHabitsService)(nil).CreateHabit), ctx, uid, req)
}

// DeleteHabit mocks base method.
func (m *MockHabitsService) DeleteHabit(ctx context.Context, habitID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHabit", ctx, habitID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHabit indicates an expected call of DeleteHabit.
func (mr *MockHabitsServiceMockRecorder) DeleteHabit(ctx, habitID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHabit", reflect.TypeOf((*MockHabitsService)(nil).DeleteHabit), ctx, habitID, userID)
}

// GetHabit mocks base method.
func (m *MockHabitsService) GetHabit(ctx context.Context, habitID, userID uuid.UUID) (*entity.Habit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHabit", ctx, habitID, userID)
	ret0, _ := ret[0].(*entity.Habit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHabit indicates an expected call of GetHabit.
func (mr *MockHabitsServiceMockRecorder) GetHabit(ctx, habitID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHabit", reflect.TypeOf((*MockHabitsService)(nil).GetHabit), ctx, habitID, userID)
}

// GetUserHabits mocks base method.
func (m *MockHabitsService) GetUserHabits(ctx context.Context, uid uuid.UUID, pagination service.PaginationOpts) ([]*entity.Habit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserHabits", ctx, uid, pagination)
	ret0, _ := ret[0].([]*entity.Habit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserHabits indicates an expected call of GetUserHabits.
func (mr *MockHabitsServiceMockRecorder) GetUserHabits(ctx, uid, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHabits", reflect.TypeOf((*MockHabitsService)(nil).GetUserHabits), ctx, uid, pagination)
}

// MockHabitChecksService is a mock of HabitChecksService interface.
type MockHabitChecksService struct {
	ctrl     *gomock.Controller
	recorder *MockHabitChecksServiceMockRecorder
	isgomock struct{}
}

// MockHabitChecksServiceMockRecorder is the mock recorder for MockHabitChecksService.
type MockHabitChecksServiceMockRecorder struct {
	mock *MockHabitChecksService
}

// NewMockHabitChecksService creates a new mock instance.
func NewMockHabitChecksService(ctrl *gomock.Controller) *MockHabitChecksService {
	mock := &MockHabitChecksService{ctrl: ctrl}
	mock.recorder = &MockHabitChecksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHabitChecksService) EXPECT() *MockHabitChecksServiceMockRecorder {
	return m.recorder
}

// CheckHabit mocks base method.
func (m *MockHabitChecksService) CheckHabit(ctx context.Context, habitID, userID uuid.UUID, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHabit", ctx, habitID, userID, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckHabit indicates an expected call of CheckHabit.
func (mr *MockHabitChecksServiceMockRecorder) CheckHabit(ctx, habitID, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHabit", reflect.TypeOf((*MockHabitChecksService)(nil).CheckHabit), ctx, habitID, userID, date)
}

// GetHabitChecks mocks base method.
func (m *MockHabitChecksService) GetHabitChecks(ctx context.Context, habitID, userID uuid.UUID, from, to time.Time) ([]entity.HabitCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHabitChecks", ctx, habitID, userID, from, to)
	ret0, _ := ret[0].([]entity.HabitCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHabitChecks indicates an expected call of GetHabitChecks.
func (mr *MockHabitChecksServiceMockRecorder) GetHabitChecks(ctx, habitID, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHabitChecks", reflect.TypeOf((*MockHabitChecksService)(nil).GetHabitChecks), ctx, habitID, userID, from, to)
}

// GetHabitStats mocks base method.
func (m *MockHabitChecksService) GetHabitStats(ctx context.Context, habitID, userID uuid.UUID) (*entity.HabitStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHabitStats", ctx, habitID, userID)
	ret0, _ := ret[0].(*entity.HabitStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHabitStats indicates an expected call of GetHabitStats.
func (mr *MockHabitChecksServiceMockRecorder) GetHabitStats(ctx, habitID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHabitStats", reflect.TypeOf((*MockHabitChecksService)(nil).GetHabitStats), ctx, habitID, userID)
}

// UncheckHabit mocks base method.
func (m *MockHabitChecksService) UncheckHabit(ctx context.Context, habitID, userID uuid.UUID, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UncheckHabit", ctx, habitID, userID, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// UncheckHabit indicates an expected call of UncheckHabit.
func (mr *MockHabitChecksServiceMockRecorder) UncheckHabit(ctx, habitID, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UncheckHabit", reflect.TypeOf((*MockHabitChecksService)(nil).UncheckHabit), ctx, habitID, userID, date)
}
