version: "3.9"

services:
  postgres:
    image: postgres:17.5-alpine3.22
    hostname: postgres
    container_name: habit_tracker_postgres
    ports:
      - "5432:5432"
    volumes:
      - habittracker_pgdata:/var/lib/postgresql/data/pgdata
      - ../migrations:/docker-entrypoint-initdb.d
    env_file:
      - ../configs/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - htracker_data_network


volumes:
  habittracker_pgdata:

networks:
  htracker_data_network:
